#!/bin/sh

echo =====   Dryrun   =====
echo Running ......
1927 dryrun ass2b Makefile dracula.c hunter.c GameView.c GameView.h DracView.c DracView.h HunterView.c HunterView.h Queue.c Queue.h &> log
echo Done!
