#!/bin/sh

echo =====   Cleaning all the old .o executable files by make clean   =====
make clean
echo ""

echo =====   Compiling the Programs   =====
make
echo ""

echo =====   Testing GameView   =====
./testGameView
echo ""

echo =====   Testing HunterView =====
./testHunterView
echo ""

echo =====   Testing DracView   =====
./testDracView
echo ""

echo =====   Valgrind Test   =====
echo ""
echo =====   valgrind ./testGameView   =====
valgrind ./testGameView
echo ""

echo =====   valgrind ./testHunterView   =====
valgrind ./testHunterView
echo ""

echo =====   valgrind ./testDracView   =====
valgrind ./testDracView
echo ""

echo DONE!
