#!/bin/sh

echo =====   Cleaning all the old .o executable files by make clean   =====
make clean
echo ""

echo =====   Compiling the Programs   =====
make
echo ""

echo =====   Test ***View   =====
./testGameView
echo ""
./testHunterView
echo ""
./testDracView
echo ""

echo DONE!
